---
version: 2.3.0
files:
  gradle.properties: version=%.%.%
  README.md:
  - coveralls-gradle-plugin v%.%.%
  - org.kt3k.gradle.plugin:coveralls-gradle-plugin:%.%.%
  build.gradle:
  - name = '%.%.%'
  - vcsTag = 'v%.%.%'
