---
version: 2.6.1
files:
  gradle.properties: version=%.%.%
  README.md:
  - coveralls-gradle-plugin v%.%.%
  - id "com.github.kt3k.coveralls" version "%.%.%"
  build.gradle:
  - name = '%.%.%'
  - vcsTag = 'v%.%.%'
