---
version: 2.6.3
files:
  README.md:
  - coveralls-gradle-plugin v%.%.%
  - id "com.github.kt3k.coveralls" version "%.%.%"
  build.gradle:
  - name = '%.%.%'
  - vcsTag = 'v%.%.%'
  - version '%.%.%'
