# .travis.yml of coveralls-gradle-plugin

language: groovy

jdk:
- oraclejdk6
- oraclejdk7

env:
- TERM=dumb

after_success:
- gradle cobertura
- ./coveralls.groovy

after_failure:
- gradle clean check --debug
