# .travis.yml of coveralls-gradle-plugin

language: groovy

jdk:
- oraclejdk7

env:
- TERM=dumb

after_success:
- gradle cobertura
- ./coveralls.groovy

script:
- a
- gradle check

after_failure:
- gradle clean check --debug
